#!/usr/bin/env node
/**
 * NIFIKISHE verification tool.
 *
 * Usage:
 *   node tools/verify.js            static integrity checks only
 *   node tools/verify.js --live     also checks a running server on PORT (default 3000)
 *
 * Static checks: JSON data integrity, JS syntax, inline handler/DOM id wiring,
 * and CSS coverage for classes generated by JavaScript.
 */
const fs = require('fs');
const path = require('path');
const http = require('http');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
const pub = path.join(root, 'public');
const problems = [];
const notes = [];

function read(p) {
  return fs.readFileSync(p, 'utf8');
}

// --- 1. JSON data files -----------------------------------------------------
const dataDir = path.join(root, 'data');
fs.readdirSync(dataDir).filter(f => f.endsWith('.json')).forEach(f => {
  try {
    const parsed = JSON.parse(read(path.join(dataDir, f)));
    const size = Array.isArray(parsed) ? parsed.length + ' records' : 'object';
    notes.push('data/' + f + ' parsed (' + size + ')');
  } catch (err) {
    problems.push('data/' + f + ' is not valid JSON: ' + err.message);
  }
});

// --- 2. JavaScript syntax ---------------------------------------------------
['public/js/app.js', 'public/js/i18n.js', 'public/js/map-service.js', 'public/js/live-gps.js', 'public/js/admin-panel.js', 'public/sw.js', 'server.js']
  .forEach(rel => {
    try {
      execFileSync(process.execPath, ['--check', path.join(root, rel)], { stdio: 'pipe' });
      notes.push(rel + ' syntax OK');
    } catch (err) {
      problems.push(rel + ' syntax error: ' + String(err.stderr || err.message).split('\n')[0]);
    }
  });

// --- 3. HTML <-> JS wiring --------------------------------------------------
const html = read(path.join(pub, 'index.html'));
const js = ['app.js', 'i18n.js', 'map-service.js', 'live-gps.js', 'admin-panel.js']
  .map(f => read(path.join(pub, 'js', f))).join('\n');
const css = read(path.join(pub, 'css', 'style.css'));

const handlers = new Set();
for (const m of html.matchAll(/on(?:click|input|change)\s*=\s*"([^"]+)"/g)) {
  for (const c of m[1].matchAll(/([A-Za-z_$][\w$]*)\s*\(/g)) handlers.add(c[1]);
}
const defined = new Set();
for (const m of js.matchAll(/(?:^|\s)function\s+([A-Za-z_$][\w$]*)|window\.([A-Za-z_$][\w$]*)\s*=/gm)) {
  if (m[1]) defined.add(m[1]);
  if (m[2]) defined.add(m[2]);
}
[...handlers].filter(h => !defined.has(h)).forEach(h => problems.push('inline handler not defined: ' + h));

const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(x => x[1]));
[...new Set([...js.matchAll(/getElementById\(\s*'([^']+)'\s*\)/g)].map(x => x[1]))]
  // adminKeyInput is rendered at runtime inside the admin modal by admin-panel.js
  .filter(id => id !== 'adminKeyInput')
  .filter(id => !ids.has(id))
  .forEach(id => problems.push('getElementById target missing from HTML: ' + id));

// --- 4. i18n coverage -------------------------------------------------------
const i18nKeys = new Set([...html.matchAll(/data-i18n(?:-ph)?="([^"]+)"/g)].map(x => x[1]));
const i18nSrc = read(path.join(pub, 'js', 'i18n.js'));
const swBlock = i18nSrc.slice(i18nSrc.indexOf('sw: {'), i18nSrc.indexOf('en: {'));
const enBlock = i18nSrc.slice(i18nSrc.indexOf('en: {'));
[...i18nKeys].forEach(k => {
  if (!swBlock.includes(k + ':')) problems.push('i18n key missing in SW dictionary: ' + k);
  if (!enBlock.includes(k + ':')) problems.push('i18n key missing in EN dictionary: ' + k);
});
notes.push('data-i18n keys checked: ' + i18nKeys.size);

// --- 5. CSS coverage for JS-generated classes -------------------------------
const generated = ['route-card-body', 'route-title', 'route-metric-pill', 'route-time-box', 'item-title', 'item-sub', 'vehicle-preview-img', 'autocomplete-item', 'live-vehicle-marker', 'gps-on'];
generated.filter(c => !css.includes('.' + c)).forEach(c => problems.push('CSS rule missing for JS-generated class: ' + c));

// --- 5b. Brand-name guard: NIFIKISHE must never be translated ---------------
try {
  const swBlockB = i18nSrc.slice(i18nSrc.indexOf('sw: {'), i18nSrc.indexOf('en: {'));
  const enBlockB = i18nSrc.slice(i18nSrc.indexOf('en: {'));
  const brandOk = s => /appName:\s*'NIFIKISHE'/.test(s) && /ctaNifikishe:\s*'NIFIKISHE'/.test(s);
  if (!brandOk(swBlockB)) problems.push('brand guard: SW appName/ctaNifikishe must be exactly NIFIKISHE');
  if (!brandOk(enBlockB)) problems.push('brand guard: EN appName/ctaNifikishe must be exactly NIFIKISHE');
  const manifest = JSON.parse(read(path.join(pub, 'manifest.json')));
  if (manifest.short_name !== 'NIFIKISHE') problems.push('brand guard: manifest short_name must be NIFIKISHE');
  if (!String(manifest.name).startsWith('NIFIKISHE')) problems.push('brand guard: manifest name must start with NIFIKISHE');
  notes.push('brand guard: NIFIKISHE untranslated in SW/EN/manifest');
} catch (err) {
  problems.push('brand guard check failed: ' + err.message);
}

// --- 6. Optional live server checks ----------------------------------------
const live = process.argv.includes('--live');
if (live) {
  const port = process.env.PORT || 3000;
  const routes = ['/', '/css/style.css', '/js/app.js', '/js/live-gps.js', '/manifest.json', '/sw.js', '/icons/icon-512.svg',
    '/images/daladala.svg', '/images/brt.svg', '/healthz', '/api/cities', '/api/search?q=kariakoo',
    '/api/complex-areas/kariakoo', '/api/admin/overview', '/api/live/vehicles?city=dar-es-salaam',
    '/api/live/nearby?lat=-6.7885&lng=39.2089&city=dar-es-salaam'];
  const probe = p => new Promise(resolve => {
    const req = http.get({ host: 'localhost', port, path: p }, res => {
      let n = 0;
      res.on('data', c => (n += c.length));
      res.on('end', () => resolve({ p, status: res.statusCode, size: n }));
    });
    req.on('error', e => resolve({ p, status: 0, error: e.message }));
    req.setTimeout(5000, () => { req.destroy(); resolve({ p, status: 0, error: 'timeout' }); });
  });
  Promise.all(routes.map(probe)).then(results => {
    results.forEach(r => {
      if (r.status === 200) notes.push('live ' + r.p + ' -> 200 (' + r.size + ' bytes)');
      else problems.push('live ' + r.p + ' -> ' + (r.status || r.error));
    });
    report();
  });
} else {
  report();
}

function report() {
  console.log('NIFIKISHE verification report');
  console.log('='.repeat(46));
  notes.forEach(n => console.log('  ok   ' + n));
  console.log('');
  if (problems.length) {
    console.log(problems.length + ' problem(s):');
    problems.forEach(p => console.log('  !!   ' + p));
    process.exit(1);
  }
  console.log('All checks passed.');
}
